Repository amoebajs/builder, pull requests merged in 2020-01, with the labels that each got.

#2 dev update
  LICENSE
  package.json
  scripts/demo.json
  scripts/demo.yaml
  src/core/base/directive.ts
  src/core/base/index.ts
  src/core/component.ts
  src/core/decorators/index.ts
  src/core/decorators/prop.ts
  src/core/decorators/property.ts
  src/core/decorators/react.ts
  src/core/index.public.ts
  src/core/libs/attach.basic.ts
  src/core/libs/helper.basic.ts
  src/core/libs/index.ts
  src/core/libs/render.react.ts
  src/factory/base.ts
  src/factory/node.ts
  src/factory/web.ts
  src/index.ts
  src/index.websdk.ts
  src/plugins/components/css-grid.component.ts
  src/providers/builder.ts
  src/providers/entities/component.react.ts
  src/providers/entities/directive.react.ts
  src/providers/entity-helper/helper.basic.ts
  src/providers/entity-helper/helper.react.ts
  src/providers/entity-helper/index.ts
  src/providers/entity-helper/render.react.ts
  src/providers/entity-parser/basic.ts
  src/providers/entity-parser/react.ts
  src/providers/global-map.ts
  src/providers/index.ts
Labels: enhancement, feature

#4 rebuild lifecycle calls
  package.json
  scripts/compile.ts
  src/core/component.ts
  src/providers/entity-parser/basic.ts
Labels: enhancement

#6 support transpileModule for builder.createSource
  scripts/compile.ts
  src/providers/builder.ts
  src/providers/webpack/config.ts
Labels: feature

#7 directive/component inputs support syntax expression
  package.json
  scripts/demo.yaml
  src/core/base/common.ts
  src/core/child-ref.ts
  src/core/decorators/property.ts
  src/core/libs/attach.basic.ts
  src/plugins/components/css-grid.component.ts
  src/plugins/components/zent-button.component.ts
  src/providers/builder.ts
  src/providers/entities/component.react.ts
  src/providers/entity-helper/helper.react.ts
  src/providers/entity-helper/render.react.ts
  src/providers/entity-parser/basic.ts
  src/providers/webpack/config.ts
  src/providers/webpack/plugins/plugins.contract.ts
  src/providers/webpack/plugins/plugins.node.ts
  yarn.lock
Labels: enhancement, feature

#8 Feature/zent form
  package.json
  scripts/compile.ts
  scripts/demo.yaml
  src/core/decorators/base.ts
  src/core/decorators/prop.ts
  src/plugins/components/common.module.ts
  src/plugins/components/css-grid.component.ts
  src/plugins/components/zent-form.component.ts
  src/plugins/directives/common.module.ts
  src/plugins/directives/zent-action-button.directive.ts
  src/plugins/directives/zent-field-value.component.ts
  src/plugins/directives/zent-form.directive.ts
  src/plugins/directives/zent-input.directive.ts
  src/plugins/directives/zent-select.directive.ts
  src/plugins/directives/zent-switch.directive.ts
  src/providers/entities/component.react.ts
  src/providers/entity-helper/helper.basic.ts
  src/providers/entity-helper/helper.react.ts
  src/providers/entity-helper/render.react.ts
  src/providers/entity-parser/basic.ts
  src/providers/entity-parser/react.ts
  src/utils/index.ts
Labels: enhancement, feature

#10 Feature: composite directive
  scripts/demo.yaml
  src/core/component.ts
  src/core/decorators/composite.ts
  src/core/decorators/index.ts
  src/core/libs/composite.basic.ts
  src/core/libs/index.ts
  src/factory/base.ts
  src/plugins/components/zent-form.component.ts
  src/plugins/directives/zent-base-css.directive.ts
  src/providers/entity-helper/helper.react.ts
  src/providers/entity-parser/basic.ts
  src/providers/entity-parser/react.ts
  src/providers/global-map.ts
Labels: feature
